config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'post_images/index'
  end
# admin
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
# user
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

# admin
  namespace :admins do
  	root 'home#top'
  	resources :themes, except: [:new, :show]
	resources :user_dates, only: [:index, :show, :edit, :update]
	resources :post_images, only: [:index, :destroy]
  end

# user
  scope module: :users do
	root 'home#top'
  	resources :themes, except: [:new, :edit] do
	  resources :post_images, only: [:new, :create]
  	end
  	resources :post_images do
  	  resource :likes, only:    [:create, :destroy]
  	  resources :image_comments, only: [:create, :destroy]
	end
	get 'tags/:tag', to: 'post_images#index', as: :tag #投稿タグリンクのルーティング
  	resources :users, only: [:show, :edit, :update] do
  	  resource :relationships, only: [:create, :destroy]
  	  member do
  	  	get :withdrow, :follows, :followers, :likes
  	  	patch :switch
  	  end
  	end
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins/home_controller.rb
class Admins::HomeController < ApplicationController
	before_action :authenticate_admin!
	def top
	end
end

app/controllers/users/home_controller.rb
class Users::HomeController < ApplicationController
  def top
  end
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/users/home_helper.rb
module Users::HomeHelper
end

app/views/admins/home/top.html.erb
<div class="container">
 <div class="row mt-5">
     <div class="col-sm-6 justify-content-around"> 
        <%= render partial: 'layouts/flashes' %>

        <%= link_to "テーマ管理", admins_themes_path, class:"btn btn-info" %>
        <%= link_to "ユーザー管理", admins_user_dates_path, class:"btn btn-info" %>
        <%= link_to "投稿画像管理", admins_post_images_path, class:"btn btn-info" %>
     </div>
 </div>
</div>