config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'post_images/index'
  end
# admin
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
# user
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

# admin
  namespace :admins do
  	root 'home#top'
  	resources :themes, except: [:new, :show]
	resources :user_dates, only: [:index, :show, :edit, :update]
	resources :post_images, only: [:index, :destroy]
  end

# user
  scope module: :users do
	root 'home#top'
  	resources :themes, except: [:new, :edit] do
	  resources :post_images, only: [:new, :create]
  	end
  	resources :post_images do
  	  resource :likes, only:    [:create, :destroy]
  	  resources :image_comments, only: [:create, :destroy]
	end
	get 'tags/:tag', to: 'post_images#index', as: :tag #投稿タグリンクのルーティング
  	resources :users, only: [:show, :edit, :update] do
  	  resource :relationships, only: [:create, :destroy]
  	  member do
  	  	get :withdrow, :follows, :followers, :likes
  	  	patch :switch
  	  end
  	end
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/theme.rb
class Theme < ApplicationRecord
	validates :title, presence: true, uniqueness: true
	validates :create_user_id, presence: true, if: :created_user?
	has_many :post_images

	def created_user?
		self.admin == false
	end

	def self.search(search) #テーマタイトルの検索
	 if search # 非公開のテーマは除く
		Theme.where(is_enabled: true).where(['title LIKE ?', "%#{search}%"])
	 else
		Theme.where(is_enabled: true)
	 end
	end
end

app/controllers/admins/themes_controller.rb
class Admins::ThemesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_theme, only: [:edit, :update, :destroy]

  def index
    @theme = Theme.new
    themes = Theme.order(:title).all

    array = [] #テーマ部屋と作成したユーザーの情報を取ってビューでeachを回すために配列を用意
    themes.each do |theme|
      hash = {
        :theme => theme,
        :create_user => theme.create_user_id.present? ? User.find(theme.create_user_id) : "" #create_user_idをUserから参照：nill判定
      }
      array.push(hash)
    end
      @view_themes = Kaminari.paginate_array(array).page(params[:page]).per(12) #配列用のページネーションメソッド
      page_num = Kaminari.paginate_array(array).page(params[:page]).current_page #現在のページ番号を取得
      @base_level = (page_num-1)*12 #通し番号のベースの作成
  end
  def create
    @theme = Theme.new(theme_params)
    @theme.admin = true
    if @theme.save
       flash[:success] = 'テーマを作成しました！'
       redirect_to admins_themes_path
    else
       flash[:danger] = '同タイトルが存在します'
       redirect_to admins_themes_path
    end
  end

  def destroy
    @theme.destroy
    flash[:danger] = 'テーマを削除しました'
    redirect_to admins_themes_path
  end

  def edit
  end

  def update
    if @theme.update(theme_params)
       flash[:success] = 'テーマを編集しました！'
       redirect_to admins_themes_path
    else
       flash.now[:danger] = 'タイトルを入力してください'
       render :edit
    end
  end

  private
   def set_theme
      @theme = Theme.find(params[:id])
   end
   def theme_params
      params.require(:theme).permit(:title, :is_enabled)
   end
end

app/controllers/users/themes_controller.rb
class Users::ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :update, :destroy]
  before_action :forbit_test_user, only: [:create, :update, :destroy]
  before_action :forbit_unauthorized_user, only: [:create, :update, :destroy]
  def index
      @theme = Theme.new
    if params[:search] #検索が含まれていたら
      @themes = Theme.search(params[:search]).page(params[:page]).per(12)
    else
      @themes = Theme.where(is_enabled: true).order(:title).page(params[:page]).per(12)
    end
  end

  def create
      @theme = Theme.new(theme_params)
      @theme.create_user_id = current_user.id
   if @theme.save
       flash[:success] = 'テーマを作成しました！'
       redirect_to themes_path
   else
       flash.now[:danger] = 'テーマを作成できませんでした。'
       @themes = Theme.order(:title).page(params[:page]).per(12)
       render :index
   end
  end

  def show
    @post_images = @theme.post_images.page(params[:page]).per(24)
  end

  def update
    if @theme.update(theme_params)
      flash[:success] = 'テーマを編集しました！'
      redirect_to theme_path(@theme)
    else
      flash.now[:danger] = '編集できませんでした'
      render :show
    end
  end

  def destroy
    @theme.update(is_enabled: false) # 論理削除
    flash.now[:danger] = '作成したテーマを削除しました'
    @theme = Theme.new
    redirect_to themes_path
  end

  private
  def set_theme
    @theme = Theme.find(params[:id])
  end

  def theme_params
    params.require(:theme).permit(:title, :is_enabled)
  end

  def forbit_test_user
    if current_user.email == "test@example.com"
      flash[:danger]= "テストユーザーのためテーマの作成はできません"
      redirect_to themes_path
    end
  end

  def forbit_unauthorized_user
    if current_user.achivement == "BEGINNER" || current_user.achivement == "ROOKIE"
      flash[:danger]="権限がありません"
      redirect_to themes_path
    end
  end
end

app/helpers/admins/themes_helper.rb
module Admins::ThemesHelper
end

app/helpers/users/themes_helper.rb
module Users::ThemesHelper
end

app/views/admins/themes/edit.html.erb
<h2>テーマ編集画面</h2>

<%= render partial: 'layouts/flashes' %>

<%= form_for(@theme, url: admins_theme_path) do |f| %>
  <div class="form-group mb-2 form-inline">
    <%= f.text_field :title, class: "form-control" %>
    <div class="form-check ml-2">
      <%= f.radio_button :is_enabled, :true %>
      <%= f.label :is_enabled, "公開" %>
      <%= f.radio_button :is_enabled, :false %>
      <%= f.label :is_enabled, "非公開" %>
    </div>
    <%= f.submit "変更を保存", class: "btn btn-primary ml-2" %>
  </div>
 <% end %>

app/views/admins/themes/index.html.erb
<div class="container">
  <h2>テーマ追加・一覧画面</h2>

        <%= render partial: 'layouts/flashes' %>

    <div class="row d-flex justify-content-center">
    <%= form_for(@theme, url:admins_themes_path) do |f| %>
        <div class="form-group mb-2 form-inline">
        <%= f.text_field :title, required:true ,class: "form-control" %>
        <div class="form-check ml-2">
          <%= f.radio_button :is_enabled, :true %>
          <%= f.label :is_enabled, "公開" %>
          <%= f.radio_button :is_enabled, :false %>
          <%= f.label :is_enabled, "非公開" %>
        </div>
        <%= f.submit "追加", class: "btn btn-primary ml-2" %>
        </div>
    <% end %>
    </div>

    <div class="row">

      <table class="table table-bordered">
        <thead>
          <tr>
          <th>No.</th>
          <th>タイトル</th>
          <th>投稿数</th>
          <th>公開ステータス</th>
          <th>作成者</th>
          <th colspan="2">管理</th>
          </tr>
        </thead>

        <tbody>
        <% @view_themes.each.with_index(1) do |theme, i| %>
          <tr>
          <td><%= @base_level + i %></td>
          <td><%= theme[:theme].title %></td>
          <td><%= theme[:theme].post_images.count %>
          <td>
            <% if theme[:theme].is_enabled == true %>
              公開
          　<% else %>
              非公開
            <% end %>
          </td>
          <td>
            <% if theme[:create_user].present? %>
              <%= link_to theme[:create_user].name, user_path(theme[:create_user].id) %>
            <% else %>
               管理者
            <% end %>
          </td>
          <td><%= link_to "編集する", edit_admins_theme_path(theme[:theme]) %></td>
          <td><% if theme[:theme].post_images.empty? %>
              <%= link_to "削除する", admins_theme_path(theme[:theme]), method: :delete, data: { confirm: '削除しますか?' } %>
              <% else %>
              すでに投稿が存在します。
              <% end %>
          </td>
          </tr>
          <% end %>
      </table>

    </div>

  <div class="row d-flex justify-content-center">
    <%= paginate @view_themes %>
  </div>

</div><!--container-->