config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'post_images/index'
  end
# admin
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
# user
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

# admin
  namespace :admins do
  	root 'home#top'
  	resources :themes, except: [:new, :show]
	resources :user_dates, only: [:index, :show, :edit, :update]
	resources :post_images, only: [:index, :destroy]
  end

# user
  scope module: :users do
	root 'home#top'
  	resources :themes, except: [:new, :edit] do
	  resources :post_images, only: [:new, :create]
  	end
  	resources :post_images do
  	  resource :likes, only:    [:create, :destroy]
  	  resources :image_comments, only: [:create, :destroy]
	end
	get 'tags/:tag', to: 'post_images#index', as: :tag #投稿タグリンクのルーティング
  	resources :users, only: [:show, :edit, :update] do
  	  resource :relationships, only: [:create, :destroy]
  	  member do
  	  	get :withdrow, :follows, :followers, :likes
  	  	patch :switch
  	  end
  	end
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/achivement_history.rb
class AchivementHistory < ApplicationRecord
    belongs_to :user
    enum achivement: [:BEGINNER, :ROOKIE, :CHALLENGER, :MASTER]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_comment.rb
class ImageComment < ApplicationRecord
	belongs_to :user
	belongs_to :post_image
	validates :comment, presence: true, length: { maximum: 100 }
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  # validates :image_id, file_content_type: { allow: ['image/jpeg', 'image/png'] }
  validates :caption, length: { maximum: 100 }
  attachment :image, type: :image
  acts_as_taggable
  belongs_to :user
  belongs_to :theme
  has_many :image_comments, dependent: :destroy
  has_many :likes,			dependent: :destroy

  # 既に引数のユーザーがいいねをクリエイトしているか、引数がない場合はスルー
  def liked_by?(user)
    if user
      likes.where(user_id: user.id).exists?
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name:"User" #フォローする人
	belongs_to :follower,  class_name:"User" #フォローされる人
end

app/models/theme.rb
class Theme < ApplicationRecord
	validates :title, presence: true, uniqueness: true
	validates :create_user_id, presence: true, if: :created_user?
	has_many :post_images

	def created_user?
		self.admin == false
	end

	def self.search(search) #テーマタイトルの検索
	 if search # 非公開のテーマは除く
		Theme.where(is_enabled: true).where(['title LIKE ?', "%#{search}%"])
	 else
		Theme.where(is_enabled: true)
	 end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length:{ minimum:2, maximum: 20}
  validates	:introduction, length: { maximum: 150 }
  # refaile
  attachment :profile_image, type: :image
  # 称号設定 0=beginner
  enum achivement: [:BEGINNER, :ROOKIE, :CHALLENGER, :MASTER]
  # リレーション
  has_many :post_images, dependent: :destroy
  has_many :likes,		 dependent: :destroy
  has_many :achivement_histories
  # ユーザーがお気に入りした投稿画像を集める
  has_many :likes_post_images, through: :likes, source: :post_image
  has_many :image_comments, dependent: :destroy
  # フォローする側のユーザー視点
  has_many :active_relationships, class_name:"Relationship", foreign_key:"following_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  # フォローされる側のユーザー視点
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user) #フォロー側から見てフォローを既にしているかどうか。
    if user
      passive_relationships.find_by(following_id: user.id).present?
    end
  end

  def appraise_user! #ユーザーの合計いいね数に応じて評価をして称号を与える
    total_likes = Like.where(post_image_id: self.post_images.ids).size
    case total_likes
    when 1..5
      self.achivement = "BEGINNER"
    when 6..10
      self.achivement = "ROOKIE"
    when 11..15
      self.achivement = "CHALLENGER"
    when 16..40
      self.achivement = "MASTER"
    end
    if will_save_change_to_attribute?(:achivement) #現状の称号と変化があればヒストリーを記録する。
      achivement_histories.new(achivement: self.achivement)
      save!
    end
  end
end

app/controllers/admins/user_dates_controller.rb
class Admins::UserDatesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user , except: [:index]
  def index
    @users = User.page(params[:page]).per(10)
    page_num = User.page(params[:page]).current_page
    @base_level = (page_num-1)*10
  end

  def show
    @user_total_likes = Like.where(post_image_id: @user.post_images.ids).size
  end

  def edit
  end

  def update
    if @user.update(user_params)
       flash[:success] = 'ユーザー情報を変更しました！'
       redirect_to admins_user_date_path(@user)
    else
       flash.now[:danger] = '変更に失敗しました。'
       render :edit
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :is_enabled)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

   after_action :store_action
  
   def store_action
     return unless request.get? # /users/sign_in, /users/sign_up, /users/passwordはsessionに記憶しない。
     if (request.path != "/users/sign_in" &&
         request.path != "/users/sign_up" &&
         request.path != "/users/password" &&
         !request.xhr?) # don't store ajax calls
       session[:previous_url] = request.fullpath 
     end
   end

   protected
   def configure_permitted_parameters
   	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   end
end

app/controllers/users/home_controller.rb
class Users::HomeController < ApplicationController
  def top
  end
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/admins/post_images_helper.rb
module Admins::PostImagesHelper
end

app/helpers/admins/themes_helper.rb
module Admins::ThemesHelper
end

app/helpers/admins/user_dates_helper.rb
module Admins::UserDatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def achivement_image_name(achivement) # ユーザーの称号に応じて画像を変更する。
        case achivement
        when "BEGINNER"
         'begginer.png'
        when "ROOKIE"
         'rookie.png'
        when "CHALLENGER"
         'challenger.png'
        when "MASTER"
         'master.png'
        end 
    end
    
    def achivement_check(achivement) # ユーザーの称号でボタン権限をつける
         achivement == "CHALLENGER" || achivement == "MASTER"
    end
        
end

app/helpers/users/home_helper.rb
module Users::HomeHelper
end

app/helpers/users/likes_helper.rb
module Users::LikesHelper
end

app/helpers/users/post_images_helper.rb
module Users::PostImagesHelper
end

app/helpers/users/themes_helper.rb
module Users::ThemesHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/user_dates/edit.html.erb
<div class="container my-5">
  <div class="row">
    <h2>ユーザー編集画面</h2>
  </div>
  <%= render partial: 'layouts/flashes' %>

    <div class="row mt-3 flex-column align-items-center">

      <%= form_for (@user), url: {controler: "admins/user_dates", action: "show" } do |f| %>

        <div class="form-group row">
          <%= f.label :会員id, class: "col-sm-4" %>
          <%= f.label @user.id, class: "col-sm-8" %>
        </div>

        <div class="form-group">
          <%= f.label :プロフィールイメージ %>
          <%= attachment_image_tag @user, :profile_image, :fill,60,60, fallback: 'no_image_user.jpg', size: '60x60', class: "rounded" %><br>
          <%= f.attachment_field :profile_image %>
        </div>

        <div class="form-group row">
          <%= f.label :ニックネーム, class: "col-sm-5" %>
          <%= f.text_field :name, class: "form-control col-sm-7" %>
        </div>

        <div class="form-group row">
          <%= f.label :自己紹介, class: "col-sm-5" %><br>
          <%= f.text_area :introduction, class: "form-control col-sm-7" %>
        </div>

        <div class="row">
          <%= f.label :会員ステータス, class: "ml-3" %>
          <div class="form-check ml-4">
            <%= f.radio_button :is_enabled, :true %>
            <%= f.label :is_enabled, "有効会員" %>
            <%= f.radio_button :is_enabled, :false %>
            <%= f.label :is_enabled, "退会済み" %>
          </div>
        </div>

        <div class="row">
          <%= f.submit "変更を保存する", class: "btn btn-primary mt-3 mx-auto" %>
        </div>

      <% end %>

  </div>
</div>

app/views/admins/user_dates/index.html.erb
<div class="container my-5">
  <div class="row">
    <h2>ユーザー情報一覧</h2>
  </div>

  <div class="row mt-3">
    <div class="col-sm-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>No.</th>
          <th>イメージ</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>投稿数</th>
          <th>ランク</th>
          <th>ステータス</th>
          <th>編集</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each.with_index(1) do |user, i| %>
        <tr>
          <td><%= @base_level + i %></td>
          <td><%= attachment_image_tag user, :profile_image, :fill,60,60, fallback: 'no_image_user.jpg', size: '60x60', class: "rounded" %>
          <td><%= link_to user_path(user) do %>
              <%= user.name %>(ユーザーページ)
              <% end %>
            </td>
          <td><%= user.email %></td>
          <td><%= user.post_images.count %>
          <td><%= user.achivement %></td>
          <td><% if user.is_enabled == true %>
              有効会員
              <% else %>
              退会済み
              <% end %>
          </td>
          <td><%= link_to '管理用画面',admins_user_date_path(user) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
 </div>


  <div class="row d-flex justify-content-center">
    <%= paginate @users %>
  </div>

</div><!--container-->

app/views/admins/user_dates/show.html.erb
<div class="container my-5">
  <div class="row">
    <h2>ユーザー情報</h2>
  </div>

  <div class="row mt-3">
    <div class="offset-sm-1 col-sm-10">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>イメージ</th>
          <th>ニックネーム</th>
          <th>メールアドレス</th>
          <th>投稿数</th>
          <th>獲得いいね数</th>
          <th>ランク</th>
          <th>ステータス</th>
          <th>編集</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= @user.id %></td>
          <td><%= attachment_image_tag @user, :profile_image, :fill,60,60, fallback: 'no_image_user.jpg', size: '60x60', class: "rounded" %>
          <td><%= @user.name %></td>
          <td><%= @user.email %></td>
          <td><%= @user.post_images.count %>
          <td><%= @user_total_likes %>
          <td><%= @user.achivement %></td>
          <td><% if @user.is_enabled == true %>
              有効会員
              <% else %>
              退会済み
              <% end %>
          </td>
          <td><%= link_to '編集する',edit_admins_user_date_path(@user) %></td>
        </tr>
      </tbody>
    </table>

    <%= render partial: 'layouts/flashes' %>
  </div>
 </div>
</div>