config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'post_images/index'
  end
# admin
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
# user
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

# admin
  namespace :admins do
  	root 'home#top'
  	resources :themes, except: [:new, :show]
	resources :user_dates, only: [:index, :show, :edit, :update]
	resources :post_images, only: [:index, :destroy]
  end

# user
  scope module: :users do
	root 'home#top'
  	resources :themes, except: [:new, :edit] do
	  resources :post_images, only: [:new, :create]
  	end
  	resources :post_images do
  	  resource :likes, only:    [:create, :destroy]
  	  resources :image_comments, only: [:create, :destroy]
	end
	get 'tags/:tag', to: 'post_images#index', as: :tag #投稿タグリンクのルーティング
  	resources :users, only: [:show, :edit, :update] do
  	  resource :relationships, only: [:create, :destroy]
  	  member do
  	  	get :withdrow, :follows, :followers, :likes
  	  	patch :switch
  	  end
  	end
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  # validates :image_id, file_content_type: { allow: ['image/jpeg', 'image/png'] }
  validates :caption, length: { maximum: 100 }
  attachment :image, type: :image
  acts_as_taggable
  belongs_to :user
  belongs_to :theme
  has_many :image_comments, dependent: :destroy
  has_many :likes,			dependent: :destroy

  # 既に引数のユーザーがいいねをクリエイトしているか、引数がない場合はスルー
  def liked_by?(user)
    if user
      likes.where(user_id: user.id).exists?
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length:{ minimum:2, maximum: 20}
  validates	:introduction, length: { maximum: 150 }
  # refaile
  attachment :profile_image, type: :image
  # 称号設定 0=beginner
  enum achivement: [:BEGINNER, :ROOKIE, :CHALLENGER, :MASTER]
  # リレーション
  has_many :post_images, dependent: :destroy
  has_many :likes,		 dependent: :destroy
  has_many :achivement_histories
  # ユーザーがお気に入りした投稿画像を集める
  has_many :likes_post_images, through: :likes, source: :post_image
  has_many :image_comments, dependent: :destroy
  # フォローする側のユーザー視点
  has_many :active_relationships, class_name:"Relationship", foreign_key:"following_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  # フォローされる側のユーザー視点
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user) #フォロー側から見てフォローを既にしているかどうか。
    if user
      passive_relationships.find_by(following_id: user.id).present?
    end
  end

  def appraise_user! #ユーザーの合計いいね数に応じて評価をして称号を与える
    total_likes = Like.where(post_image_id: self.post_images.ids).size
    case total_likes
    when 1..5
      self.achivement = "BEGINNER"
    when 6..10
      self.achivement = "ROOKIE"
    when 11..15
      self.achivement = "CHALLENGER"
    when 16..40
      self.achivement = "MASTER"
    end
    if will_save_change_to_attribute?(:achivement) #現状の称号と変化があればヒストリーを記録する。
      achivement_histories.new(achivement: self.achivement)
      save!
    end
  end
end

app/controllers/admins/post_images_controller.rb
class Admins::PostImagesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @post_images = PostImage.page(params[:page]).per(20)
    page_num = PostImage.page(params[:page]).current_page
    @base_level = (page_num - 1)*20

  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to admins_post_images_path
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/home_controller.rb
class Users::HomeController < ApplicationController
  def top
  end
end

app/controllers/users/image_comments_controller.rb
class Users::ImageCommentsController < ApplicationController
    before_action :authenticate_user!
    def create
      @post_image = PostImage.find(params[:post_image_id])
      @image_comment = current_user.image_comments.new(image_comment_params)
      @image_comment.post_image_id = @post_image.id
      if @image_comment.save
        flash[:success] = 'コメントを投稿しました'
        redirect_to post_image_path(@post_image)
      else
        flash[:danger] = 'コメントの送信に失敗しました'
        redirect_to post_image_path(@post_image)
      end
    end

    def destroy
      @post_image = PostImage.find(params[:post_image_id])
      @image_comment = current_user.image_comments.find_by(id: params[:id],post_image_id: params[:post_image_id])
      @image_comment.destroy
      flash[:warning] = 'コメントを削除しました。'
      redirect_to post_image_path(@post_image)
    end

    private
    def image_comment_params
        params.require(:image_comment).permit(:comment)
    end

end

app/controllers/users/likes_controller.rb
class Users::LikesController < ApplicationController
  before_action :authenticate_user!
  def create
    @post_image = PostImage.find(params[:post_image_id])
    like = current_user.likes.new(post_image_id: params[:post_image_id])
    ActiveRecord::Base.transaction do #いいねの数に応じてユーザーのデータを変更するためトランザクション処理
    like.save! #いいねをつける
    @post_image.user.appraise_user! #ユーザーの称号評価メソッドを行う。
    end
  end

  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    like = current_user.likes.find_by(post_image_id: params[:post_image_id])
    like.destroy
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/post_images_controller.rb
class Users::PostImagesController < ApplicationController
 before_action :set_post_image, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!, except: [:index, :show, :search]
 before_action :ensure_correct_user, only: [:edit, :destroy]
  def index
    if params[:tag]
      @post_images = PostImage.tagged_with(params[:tag]).page(params[:page]).per(30)
    else
      @post_images = PostImage.page(params[:page]).per(48).reverse_order
    end

  end

  def show
    @image_comment = ImageComment.new
  end

  def new
   if params[:theme_id]
     @theme = Theme.find(params[:theme_id])
     @post_image = PostImage.new
   else
     @post_image = PostImage.new
   end
  end

  def create
    if params[:theme_id] # テーマ部屋から投稿された場合
      @theme = Theme.find(params[:theme_id])
      @post_image = PostImage.new(post_image_params)
      @post_image.user_id = current_user.id
      @post_image.theme_id = @theme.id
      if @post_image.save
        flash[:success] = '投稿しました！'
        redirect_to theme_path(@theme.id)
      end
    else # ヘッダーメニューから投稿された場合
      @post_image = PostImage.new(post_image_params)
      @post_image.user_id = current_user.id
      if @post_image.save
        flash[:success] = '投稿しました！'
        redirect_to post_image_path(@post_image)
      else
        flash.now[:danger] = 'テーマを選択してください'
        render :new
      end
    end
  end

  def edit
  end

  def update
    if @post_image.update(post_image_params)
       flash[:success] = '編集しました！'
       redirect_to post_image_path(@post_image)
    else
       flash.now[:danger] = '編集に失敗しました'
       render :edit
    end
  end

  def destroy
    @post_image.destroy
    redirect_to post_images_path
  end

  private
  def set_post_image
    @post_image = PostImage.find(params[:id])
  end

  def post_image_params
     params.require(:post_image).permit(:image, :caption, :tag_list, :theme_id)
  end

  def ensure_correct_user
      @post_image = PostImage.find(params[:id])
   if current_user.id != @post_image.user.id
      flash[:danger] = "権限がありません"
      redirect_to user_path(current_user.id)
   end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private
  def after_sign_in_path_for(resource)
      user_path(resource)
  end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
	before_action :authenticate_user!
  def create
	@user = User.find(params[:user_id])
  	follow = current_user.active_relationships.new(follower_id: params[:user_id])
  	follow.save
  end

  def destroy
	@user = User.find(params[:user_id])
  	follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
  	follow.destroy
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  private
  def after_sign_in_path_for(resource)
    if resource.is_enabled == false    #(resource)に入った値のユーザーのステータスが退会済になっていたら強制退去
       sign_out resource
       root_path
    elsif 
       session[:previous_url] == '/'   # topページからのログインの場合はユーザーページに遷移
       user_path(resource)
    else
       session[:previous_url] || root_path # それ以外はログインが要求される前のページに遷移
    end
  end
end

app/controllers/users/themes_controller.rb
class Users::ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :update, :destroy]
  before_action :forbit_test_user, only: [:create, :update, :destroy]
  before_action :forbit_unauthorized_user, only: [:create, :update, :destroy]
  def index
      @theme = Theme.new
    if params[:search] #検索が含まれていたら
      @themes = Theme.search(params[:search]).page(params[:page]).per(12)
    else
      @themes = Theme.where(is_enabled: true).order(:title).page(params[:page]).per(12)
    end
  end

  def create
      @theme = Theme.new(theme_params)
      @theme.create_user_id = current_user.id
   if @theme.save
       flash[:success] = 'テーマを作成しました！'
       redirect_to themes_path
   else
       flash.now[:danger] = 'テーマを作成できませんでした。'
       @themes = Theme.order(:title).page(params[:page]).per(12)
       render :index
   end
  end

  def show
    @post_images = @theme.post_images.page(params[:page]).per(24)
  end

  def update
    if @theme.update(theme_params)
      flash[:success] = 'テーマを編集しました！'
      redirect_to theme_path(@theme)
    else
      flash.now[:danger] = '編集できませんでした'
      render :show
    end
  end

  def destroy
    @theme.update(is_enabled: false) # 論理削除
    flash.now[:danger] = '作成したテーマを削除しました'
    @theme = Theme.new
    redirect_to themes_path
  end

  private
  def set_theme
    @theme = Theme.find(params[:id])
  end

  def theme_params
    params.require(:theme).permit(:title, :is_enabled)
  end

  def forbit_test_user
    if current_user.email == "test@example.com"
      flash[:danger]= "テストユーザーのためテーマの作成はできません"
      redirect_to themes_path
    end
  end

  def forbit_unauthorized_user
    if current_user.achivement == "BEGINNER" || current_user.achivement == "ROOKIE"
      flash[:danger]="権限がありません"
      redirect_to themes_path
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user! , except: [:show]
  before_action :set_user
  before_action :ensure_correct_user, only: [:edit, :withdrow]
  before_action :forbit_test_user, only: [:edit, :withdrow]
  def show
    @post_images = @user.post_images #投稿画像
    @like_post_images = @user.likes_post_images #いいねした画像
    @followings = @user.followings #フォロー
    @followers = @user.followers #フォロワー
    @total_likes = Like.where(post_image_id: @user.post_images.ids).size
    @achivements = @user.achivement_histories
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = '登録情報を変更しました！'
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = '変更に失敗しました。'
      render :edit
    end
  end

  def withdrow
  end

  def switch
    if @user.update(is_enabled: false)
       sign_out current_user # サインアウト
    end
       redirect_to root_path
  end
  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
   if current_user.id != @user.id
      flash[:danger] = "権限がありません"
      redirect_to user_path(current_user.id)
   end
  end

  def forbit_test_user
    if current_user.email == "test@example.com"
       flash[:danger]= "テストユーザーのため変更できません"
       redirect_to root_path
    end
  end

end

app/helpers/admins/post_images_helper.rb
module Admins::PostImagesHelper
end

app/helpers/users/home_helper.rb
module Users::HomeHelper
end

app/helpers/users/image_comments_helper.rb
module Users::ImageCommentsHelper
end

app/helpers/users/likes_helper.rb
module Users::LikesHelper
end

app/views/users/post_images/_image_comments.html.erb
    <% post_image.image_comments.each do |image_comment|%>
     <div class="row mb-3">
      <div class="col-xs-2 ml-2">
        <%= link_to user_path(image_comment.user) do %> 
          <%= attachment_image_tag image_comment.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.png", :size => "60x60" ,class: "rounded-circle" %>
          <%= image_comment.user.name %>
        <% end %>
      </div>

      <div class="col-xs-8  offset-1">
         <%= image_comment.comment %><br><br>
         <%= image_comment.created_at.strftime('%Y/%m/%d') %>
      <% if image_comment.user == current_user %>
         <%= link_to 'コメントを削除する', post_image_image_comment_path(image_comment.post_image_id, image_comment.id), method: :delete, class: "small" %>
      <% end %>
      </div>
     </div>
     <% end %>

app/views/users/post_images/_image_index.html.erb
<% post_images.shuffle.each do |post_image| %>
  <div class="card like-hover">
      <%= link_to post_image_path(post_image) do %>
      <%= attachment_image_tag post_image, :image, format: 'jpeg', class:"card-img img-fluid" %>
      <% end %>

    <!-- 称号アイコン -->
    <div class="user_achivement-p">
      <%= image_tag achivement_image_name(post_image.user.achivement), size: '54x54' %>
    </div>

    <!-- いいねボタン -->
    <div id="likes_buttons_<%= post_image.id %>" class="likes_button">
      <%= render partial: 'users/likes/like', locals: {post_image: post_image} %>
    </div>

    <!-- ステータス -->
    <div id="likes_status_<%= post_image.id %>" class="likes_status">
      <%= render partial: 'users/likes/like_status', locals: {post_image: post_image} %>
    </div>
  </div>
<% end %>

app/views/users/post_images/edit.html.erb
<div class="container pb-4">

 <div class="row mt-3 mb-3">
  <h4 class="section-title">投稿画像編集</h4>
 </div>

   <%= form_for(@post_image, url: post_image_path(@post_image)) do |f| %>
    <div class="row">
        <div class="col-md-7">
        <div class="image_box mt-5">
            <%= attachment_image_tag @post_image, :image, class:"img-fluid " %>
        </div>
        </div>

     <div class="col-md-5">
        <div class="row border-bottom">
        <div class="user_date d-flex align-items-center mt-5">
            <%= attachment_image_tag @post_image.user, :profile_image, :fill,60,60, fallback: 'no_image.png', size: '100x100', class: "rounded-circle" %>
            <div class="user_name h3 pl-3 "><%= @post_image.user.name %></div>
            <div class="user_achivement">
              <%= image_tag achivement_image_name(@post_image.user.achivement), size: '48x48' %>
            </div>
        </div>
        </div>


        <div class="row">
            <%= f.label :caption, "投稿コメント" %>
            <%= f.text_area :caption, rows:'3', class:"form-control" %>
        </div>

        <div class="row mt-3">
            <%= f.label :theme_id, "テーマ" %>
            <%= f.collection_select :theme_id, Theme.where(is_enabled: true).order(:title), :id, :title, class: "form-control" %>
        </div>

        <div class="row mt-3">
            <%= f.label :tag_list, "タグ" %><span class="small ml-3">複数の場合は（、）で区切ってください</span><br>
            <%= f.text_field :tag_list, value: @post_image.tag_list.join('、'), class:"form-control" %>
        </div>
        <div class="row mt-5">
            <%= f.submit :"内容を変更する", class:"btn btn-primary" %>
        </div>
    <% end %>
        <div class="row mt-5">
            <%= link_to "投稿を削除する", post_image_path(@post_image.id), method: :delete, class:"btn btn-danger" , data: { confirm: 'これまでに獲得したいいねやコメントは消失しますが、よろしいですか?' } %>
        </div>
     </div>
    </div>
</div>

app/views/users/post_images/index.html.erb
<% unless params[:page] %>
<div class="jumbotron jumbotron-image jumbotron-post_image jumbotron-fluid">	
  <div class="container-fluid jumbotron-container">
      <h1 class="title image-text">インスピレーションを受ける</h1>
  </div>
</div>
<% end %>

    <div class="container-fluid mt-3">
      <%= render partial: 'layouts/flashes' %>
      <div class="row align-content-start">
        <div class="card-columns mx-4">
          <%= render partial: 'users/post_images/image_index', locals: {post_images: @post_images} %>
        </div>
      </div>
        <div class="row d-flex justify-content-center">
           <%= paginate @post_images %>
        </div>
    </div>

app/views/users/post_images/new.html.erb
<div class="container py-3">

 <div class="row mt-3 mb-3">
  <h4 class="section-title">新規投稿</h4>
 </div>

   <%= render partial: 'layouts/flashes' %>

 <!-- ジャンル部屋投稿 -->

 <% if params[:theme_id] %>

  <h5>テーマ：<%= @theme.title %></h5>

  <%= form_for(@post_image, url:theme_post_images_path(@theme.id)) do |f| %>

    <div class="row mt-3">
      <div class="form-group col-sm-12">
       <%= f.label :image, "投稿画像" %><br>
       <%= attachment_image_tag @post_image, :image, format: 'jpeg', fallback: 'no_post_image.png', class: "prev-box img-fluid", id:"img-prev" %><br>
       <%= f.attachment_field :image , required:true ,id:"post-image" ,class:"post-image mt-3"%>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-5">
       <%= f.label :caption, "投稿コメント" %><br>
       <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメント" %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-5">
       <%= f.label :tag_list, "タグ" %><span class="small ml-3">複数の場合は（、）で区切ってください</span><br>
       <%= f.text_field :tag_list, value: @post_image.tag_list.join('、'), class:"form-control", placeholder:"夜景、月" %>
      </div>
    </div>
    <br>
    <div class="row">
     <div class="col-sm-5">
       <%= f.submit "投稿する", class:"btn btn-light" %>
     </div>
 <% end %>
    </div>

<% else %>

 <!-- ヘッダー投稿 -->

  <%= form_for(@post_image, url:post_images_path) do |f| %>

    <div class="row mt-3">
      <div class="form-group col-sm-12">
       <%= f.label :image, "投稿画像" %><br>
       <%= attachment_image_tag @post_image, :image, format: 'jpeg', fallback: 'no_post_image.png', class: "prev-box img-fluid", id:"img-prev" %><br>
       <%= f.attachment_field :image , required:true ,id:"post-image" ,class:"post-image mt-3"%>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-5">
       <%= f.label :caption, "投稿コメント" %><br>
       <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメント" %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-5">
       <%= f.label :theme_id, "テーマ" %><br>
       <%= f.collection_select :theme_id, Theme.where(is_enabled: true).order(:title), :id, :title, prompt: "テーマを選択してください", class: "form-control" %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-sm-5">
       <%= f.label :tag_list, "タグ" %><span class="small ml-3">複数の場合は（、）で区切ってください</span><br>
       <%= f.text_field :tag_list, value: @post_image.tag_list.join('、'), class:"form-control", placeholder:"夜景、月、" %>
      </div>
    </div>
    <br>
    <div class="row">
     <div class="col-sm-5">
       <%= f.submit "投稿する" %>
     </div>
  <% end %>
    </div>

  <% end %>
</div>

app/views/users/post_images/show.html.erb
<div class="container">
 <div class="row">

        <!-- 投稿画像 -->
  <div class="col-md-6 d-flex justify-content-center">
        <div class="image_box like-hover my-5">
          <%= attachment_image_tag @post_image, :image, class:"img-fluid" %>
          <% if current_user == @post_image.user %>
            <div><%= link_to "編集する", edit_post_image_path(@post_image.id), class:"page-link text-dark d-inline-block mt-2" %></div>
          <% end %>
          <%= render partial: 'layouts/flashes' %>

        <!-- いいねボタン -->
          <div id="likes_buttons_<%= @post_image.id %>" class="likes_button">
          <%= render partial: 'users/likes/like', locals: {post_image: @post_image} %>
          </div>
        </div>
  </div>


        <!-- ユーザーインフォメーション -->
  <div class="col-md-5 offset-md-1">

        <!-- プロフィール -->
        <div class="row pl-3">
          <div class="user_date d-flex align-items-center mt-5">
            <%= link_to user_path(@post_image.user) do %>
            <%= attachment_image_tag @post_image.user, :profile_image, :fill,60,60, fallback: 'no_image.png', size: '100x100', class: "rounded-circle" %>
            <% end %>
            <div class="user_name h5 mx-3 "><%= link_to @post_image.user.name, user_path(@post_image.user) %></div>
            <div class="user_achivement">
              <%= image_tag achivement_image_name(@post_image.user.achivement), size: '48x48' %>
            </div>
          </div>
            <!-- フォローボタン -->
            <div id="follow_buttons_<%= @post_image.user.id %>" class="follow_button ml-2 mt-2">
              <%= render partial: 'users/users/follow_btn', locals: {user: @post_image.user} %>
            </div>
        </div>

        
            <!-- ステータス -->
        <div class="row border-bottom d-flex align-item-center pl-3">
            <div id="likes_status_<%= @post_image.id %>" class="likes_status-active pt-1">
            <%= render partial: 'users/likes/like_status', locals: {post_image: @post_image} %>
            </div>
            <div class="theme-title">
             <%= link_to @post_image.theme.title, theme_path(@post_image.theme), class:"btn btn-light ml-5"%>
            </div>
        </div>
        
            <!-- 投稿コメント -->
        <div class="row border-bottom">
          <div class="col-xs-8">
            <div class="card border-secondary mb-3">
             <div class="card-body">
              <p class="card-title text-secondary">投稿コメント</p>
              <p class="card-text"><%= @post_image.caption %></p>
             </div>
            </div>
          </div>
        </div>

            <!-- タグ -->
        <div class="row border-bottom">
          <div class="card border-secondary mb-3">
            <div class="card-body">
             <p class="card-title text-secondary">タグ</p>
             <h5 class="tag_list">
             <%= raw @post_image.tag_list.map{ |t| link_to t, tag_path(t), class:"badge badge-pill badge-success"}.join(' ') %>
             </h5>
            </div>
          </div>
        </div>

            
            <!-- コメント欄 -->
        <div id="image_comments">
          <p class="text-secondary ml-1 mt-2">コメント</p>
          <%= render partial: 'image_comments', locals: {post_image: @post_image} %>
        </div>


            <!-- コメントフォーム -->
        <div class="row border-bottom">
          <div class="col-12">
           <% if user_signed_in? %>
            <div class="form-group">
              <%= form_with model: [@post_image, @image_comment] ,local: true do |f| %>
               <%= f.text_area :comment, rows:'2', class:"form-control" %>
               <%= f.submit :"コメントする", class:"btn btn-info mt-2"%>
              <% end %>
            </div>
           <% else %>
            <p class="text-secondary">会員登録するとコメントが可能になります。</p>
           <% end %>
          </div>
        </div>

  

  </div>


 </div> <!--row-->
</div> <!--containe-->